### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by robsonpeixoto** [GoogleCloudPlatform/appengine-flask-skeleton#1]
Log from GoogleAppEngineLauncher.app 1.8.9.1049

```
*** Running dev_appserver with the following flags:
    --skip_sdk_update_check=yes --port=8080 --admin_port=8000
Python command: /opt/local/bin/python2.7
INFO     2014-01-18 12:22:14,967 devappserver2.py:671] Skipping SDK update check.
INFO     2014-01-18 12:22:15,003 api_server.py:138] Starting API server at: http://localhost:58042
INFO     2014-01-18 12:22:15,008 dispatcher.py:171] Starting module "default" running at: http://localhost:8080
INFO     2014-01-18 12:22:15,016 admin_server.py:117] Starting admin server at: http://localhost:8000
ERROR    2014-01-18 12:22:24,884 wsgi.py:262] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 298, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 84, in LoadObject
    obj = __import__(path[0])
  File "/Users/robinho/financeiro/main.py", line 10, in <module>
    from flask import Flask
  File "/Users/robinho/financeiro/server/lib/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Users/robinho/financeiro/server/lib/werkzeug/__init__.py", line 20, in <module>
    from werkzeug._compat import iteritems
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/__init__.py", line 154, in <module>
    __import__('werkzeug.exceptions')
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/http.py", line 971, in <module>
    from werkzeug.datastructures import Accept, HeaderSet, ETags, Authorization, \
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/datastructures.py", line 2612, in <module>
    from werkzeug import exceptions
ImportError: cannot import name exceptions
INFO     2014-01-18 12:22:24,911 module.py:612] default: "GET / HTTP/1.1" 500 -
ERROR    2014-01-18 12:22:25,175 wsgi.py:262] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 298, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 84, in LoadObject
    obj = __import__(path[0])
  File "/Users/robinho/financeiro/main.py", line 10, in <module>
    from flask import Flask
  File "/Users/robinho/financeiro/server/lib/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Users/robinho/financeiro/server/lib/werkzeug/__init__.py", line 20, in <module>
    from werkzeug._compat import iteritems
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/__init__.py", line 154, in <module>
    __import__('werkzeug.exceptions')
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/http.py", line 971, in <module>
    from werkzeug.datastructures import Accept, HeaderSet, ETags, Authorization, \
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/datastructures.py", line 2612, in <module>
    from werkzeug import exceptions
ImportError: cannot import name exceptions
INFO     2014-01-18 12:22:25,186 module.py:612] default: "GET / HTTP/1.1" 500 -
ERROR    2014-01-18 12:22:26,134 wsgi.py:262] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 298, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 84, in LoadObject
    obj = __import__(path[0])
  File "/Users/robinho/financeiro/main.py", line 10, in <module>
    from flask import Flask
  File "/Users/robinho/financeiro/server/lib/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Users/robinho/financeiro/server/lib/werkzeug/__init__.py", line 20, in <module>
    from werkzeug._compat import iteritems
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/__init__.py", line 154, in <module>
    __import__('werkzeug.exceptions')
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/http.py", line 971, in <module>
    from werkzeug.datastructures import Accept, HeaderSet, ETags, Authorization, \
  File "/Users/robinho/financeiro/server/lib/werkzeug/werkzeug/datastructures.py", line 2612, in <module>
    from werkzeug import exceptions
ImportError: cannot import name exceptions
INFO     2014-01-18 12:22:26,142 module.py:612] default: "GET /favicon.ico HTTP/1.1" 500 -
```

**Comment by tianhuil** [comment]
I got the same issue and it turned out to be resolved by flask versioning.  For me, `Flask==0.10` was the offending culprit and this issue seemed to have been fixed by `Flask==0.10.1`.  Hope that helps!
