### ISSUE TITLE
Local dev_appserver.py ERROR wsgi.py

### ISSUE THREAD

**Issue by billyfung** [GoogleCloudPlatform/appengine-flask-skeleton#20]
I get an error trying to run the dev_appserver on my local machine, OSX 10.11.1 

```
ERROR    2015-12-02 23:10:49,201 wsgi.py:263]
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
```

**Comment by jonparrott** [comment]
Can you tell me which version of the App Engine SDK you have?

**Comment by billyfung** [comment]
1.9.28

**Comment by jonparrott** [comment]
Can you try upgrading to 1.9.30 and trying again? I couldn't reproduce this on that version.

**Comment by billyfung** [comment]
Actually seems like it's a weird error with commenting in my code, dev_appserver works fine. Can close

**Comment by jonparrott** [comment]
Glad you got it figured out. Let us know if you have any other issues. :)
