### ISSUE TITLE
requirement file is not correct

### ISSUE THREAD

**Issue by antrianis** [GoogleCloudPlatform/appengine-flask-skeleton#28]
Traceback (most recent call last):
  File "/Users/username/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/username/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/username/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/username/gitProjects/appengine-flask-skeleton/main.py", line 4, in <module>
    from flask import Flask
  File "/Users/username/gitProjects/appengine-flask-skeleton/lib/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Users/username/gitProjects/appengine-flask-skeleton/lib/werkzeug/__init__.py", line 20, in <module>
    from werkzeug._compat import iteritems
  File "/Users/username/gitProjects/appengine-flask-skeleton/lib/werkzeug/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/Users/username/gitProjects/appengine-flask-skeleton/lib/werkzeug/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/Users/username/gitProjects/appengine-flask-skeleton/lib/werkzeug/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/Users/username/gitProjects/appengine-flask-skeleton/lib/werkzeug/werkzeug/http.py", line 1012, in <module>
    from werkzeug.datastructures import Accept, HeaderSet, ETags, Authorization, \
  File "/Users/username/gitProjects/appengine-flask-skeleton/lib/werkzeug/werkzeug/datastructures.py", line 2703, in <module>
    from werkzeug import exceptions
ImportError: cannot import name exceptions

**Comment by jonparrott** [comment]
@antrianis I'm not able to reproduce this. Can you tell me a bit more? What command are you using to run the application? What changes did you make (if any)?

**Comment by tswast** [comment]
This sample is being archived.
